In [3]:
import numpy as np
import pandas as pd
url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data'
column_names = ['MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight',
                'Acceleration', 'Model Year', 'Origin']

raw_dataset = pd.read_csv(url, names=column_names,
                          na_values='?', comment='\t',
                          sep=' ', skipinitialspace=True)

In [4]:
dataset = raw_dataset.copy()
dataset.head()

MPG  Cylinders  Displacement  Horsepower  Weight  Acceleration  \
0  18.0          8         307.0       130.0  3504.0          12.0   
1  15.0          8         350.0       165.0  3693.0          11.5   
2  18.0          8         318.0       150.0  3436.0          11.0   
3  16.0          8         304.0       150.0  3433.0          12.0   
4  17.0          8         302.0       140.0  3449.0          10.5   

   Model Year  Origin  
0          70       1  
1          70       1  
2          70       1  
3          70       1  
4          70       1

In [5]:
dataset = dataset.dropna()

In [7]:
dataset['Origin'] = dataset['Origin'].map({1: 'USA', 2: 'Europe', 3: 'Japan'})

In [9]:
dataset = pd.get_dummies(dataset, columns=['Origin'], prefix='', prefix_sep='')

In [10]:
datasetXsingle=dataset[['Horsepower']]
datasetXMulti=dataset[['Cylinders', 'Displacement', 'Horsepower', 'Weight',
                'Acceleration', 'Model Year', 'Europe','Japan','USA']]
datasetY=dataset[['MPG']]

In [15]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(datasetXsingle,datasetY)

LinearRegression()

In [16]:
reg.score(datasetXsingle,datasetY)

0.6059482578894348

In [17]:
reg.coef_

array([[-0.15784473]])

In [19]:
reg.intercept_

array([39.93586102])

In [20]:
from sklearn.linear_model import LinearRegression
reg2 = LinearRegression()
reg2.fit(datasetXMulti,datasetY)

LinearRegression()

In [22]:
reg2.score(datasetXMulti,datasetY)

0.8241994699119172

In [23]:
reg2.coef_

array([[-0.48970942,  0.02397864, -0.01818346, -0.00671038,  0.07910304,
         0.77702694,  0.80225883,  1.0254847 , -1.82774353]])

In [24]:
reg2.intercept_

array([-16.12685854])

In [25]:
from sklearn import preprocessing as p 
min_max_scaler = p.MinMaxScaler() 
normalizedData = min_max_scaler.fit_transform(datasetXMulti)

In [26]:
reg3 = LinearRegression()
reg3.fit(normalizedData,datasetY)

LinearRegression()

In [27]:
reg3.score(normalizedData,datasetY)

0.8241994699119171

In [28]:
reg3.coef_

array([[ -2.44854712,   9.27973524,  -3.34575738, -23.66752482,
          1.328931  ,   9.32432327,   0.80225883,   1.0254847 ,
         -1.82774353]])

In [29]:
reg3.intercept_

array([27.39898207])

In [30]:
from sklearn import preprocessing as p 
normalizedData = pd.get_dummies(datasetXMulti)

In [31]:
reg4 = LinearRegression()
reg4.fit(normalizedData,datasetY)

LinearRegression()

In [32]:
reg4.score(normalizedData,datasetY)

0.8241994699119172

In [33]:
reg4.coef_

array([[-0.48970942,  0.02397864, -0.01818346, -0.00671038,  0.07910304,
         0.77702694,  0.80225883,  1.0254847 , -1.82774353]])

In [34]:
reg4.intercept_

array([-16.12685854])